environment:
  my_email:
    secure: R7dZ4m7gCp+NdEN+sUnfI9NsdMh/lvBNhdqsAGO/CWg=

os: Visual Studio 2015

# Version format
version: 1.7.5.{build}

cache:
  - Source\packages -> **\packages.config   # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

branches:
  only:
    - develop-v7
    - master
    
# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=rtm  

test: 
    assemblies:
    - '**\Our.Umbraco.Nexu.*.Tests.dll'

build_script:
  - cd Packaging
  - build-appveyor.bat

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip